#!/bin/bash                                                                                                                                                                    
FLAGMATIC_PKG=/Users/srobik/Github/flagmatic-dev/pkg/
SAGE_SITE_PKGS=/Users/srobik/Downloads/sage-6.4/local/lib/python2.7/site-packages/

# remove old flagmatic versions                                                                                                                                                
cd $SAGE_SITE_PKGS
#eval "sudo rm Flagmatic*.egg-info"

# install new flagmatic version                                                                                                                                                
cd $FLAGMATIC_PKG
eval "sudo -E sage -python setup.py install"
